package Exception;

import java.util.InputMismatchException;
import java.util.Scanner;

public class Main {
    /*public static void connectTCMB() {
        //veri alma oprretorleri connectionlar vs vssvssv
        System.out.println("kur verileri alındı");
    }*/
    public static void main(String[] args)
    {
        System.out.println("Program başladı");
        Scanner input = new Scanner(System.in);
        int a, b;//double tanımlarsam infinity veriyor.
        a =1;
        b = 10;
        int c;
        int arr[]=new int[2];
        try{

            System.out.println("başladı");
            System.out.println(b / a);
            System.out.println("bitti");
            c = input.nextInt();
            arr[10]=51;

        }catch (ArithmeticException e){
            System.out.println("Aritmrtik hata");
            System.out.println(e.getMessage());
            System.out.println(e.toString());
        }catch (InputMismatchException e){
            System.out.println("yanlış veri girildi");
            System.out.println(e.getMessage());
        }catch(Exception e){
            System.out.println("array hatası var");
            System.out.println(e.getMessage());

        }
            finally {
            System.out.println("Kesin çalısması gereken yerler");//database kapatma vs
        }
        System.out.println("Program Bitti");
    }
}
